spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  ai:
    url: ${AI_URL}

swagger:
  server-url: ${SWAGGER_SERVER_URL}

cors:
  allowedOrigins:
    - ${SWAGGER_SERVER_URL}
    - ${ALLOWED_ORIGINS_PRODUCT}
    - ${ALLOWED_ORIGINS_STAGE}
    - ${ALLOWED_ORIGINS_LOCAL:http://localhost:3000}
