spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  ai:
    url: ${AI_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiration-time: 600000
  refresh-token:
    expiration-time: 86400000

swagger:
  server-url: ${SWAGGER_SERVER_URL}

cors:
  allowedOrigins:
    - ${SWAGGER_SERVER_URL}
    - ${ALLOWED_ORIGINS_PRODUCT}
    - ${ALLOWED_ORIGINS_STAGE}
    - ${ALLOWED_ORIGINS_LOCAL:http://localhost:3000}
