name: Code Review From ChatGPT

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          MODEL: gpt-4o-mini
          top_p: 1
          temperature: 1
          PROMPT: |
            Please focus only on critical errors and major issues in the code review. Provide a single, concise response that highlights the most significant problems. Avoid giving extensive feedback on minor or stylistic issues. Summarize your comments and prioritize the most impactful suggestions for improvement.
          max_tokens: 5000
          MAX_PATCH_LENGTH: 3000
