name: Code Review From ChatGPT

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Gather diff of all files
        run: git diff origin/main -- > combined_diff.txt

      - name: Perform Code Review
        uses: anc95/ChatGPT-CodeReview@main
        with:
          patch_file: combined_diff.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          MODEL: gpt-4o-mini
          top_p: 1
          temperature: 1
          max_tokens: 5000
          MAX_PATCH_LENGTH: 5000
